"""some model changes

Revision ID: 66b557571901
Revises: 1917fb907f4f
Create Date: 2024-01-16 08:09:59.020468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b557571901'
down_revision = '1917fb907f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insta_char', schema=None) as batch_op:
        batch_op.add_column(sa.Column('font_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('style_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'style', ['style_id'], ['id'])
        batch_op.create_foreign_key(None, 'font', ['font_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insta_char', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('style_id')
        batch_op.drop_column('font_id')

    # ### end Alembic commands ###
