"""empty message

Revision ID: 9617cdc7148a
Revises: 6668fabc3955
Create Date: 2024-01-28 17:14:47.460847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9617cdc7148a'
down_revision = '6668fabc3955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_cookie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_cookie', schema=None) as batch_op:
        batch_op.drop_column('expiration')

    # ### end Alembic commands ###
