"""empty message

Revision ID: 99f496306706
Revises: 66b557571901
Create Date: 2024-01-28 02:40:51.684025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f496306706'
down_revision = '66b557571901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insta_char', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.BLOB(),
               type_=sa.Unicode(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insta_char', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.Unicode(length=10),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
